/**
 * Translates genre names from English to Arabic
 * @param {string} genreNameEnglish - The genre name in English
 * @returns {string} The translated genre name in Arabic
 */
export const translateGenre = (genreNameEnglish) => {
  if (!genreNameEnglish) return "";
  
  const genreTranslations = {
    // Common genres
    "romance": "رومانسية",
    "action": "أكشن",
    "fantasy": "فانتازيا",
    "sci-fi": "خيال علمي",
    "science fiction": "خيال علمي",
    "mystery": "غموض",
    "thriller": "إثارة",
    "drama": "دراما",
    "comedy": "كوميديا",
    "horror": "رعب",
    "adventure": "مغامرة",
    
    // Additional genres
    "historical": "تاريخي",
    "slice of life": "شريحة من الحياة",
    "psychological": "نفسي",
    "supernatural": "خارق للطبيعة",
    "martial arts": "فنون قتالية",
    "cultivation": "زراعة",
    "xuanhuan": "شوانهوان",
    "xianxia": "شيانشيا",
    "wuxia": "ووشيا",
    "school life": "حياة مدرسية",
    "sports": "رياضة",
    "mecha": "ميكا",
    "game": "ألعاب",
    "virtual reality": "واقع افتراضي",
    "isekai": "إيسيكاي",
    "reincarnation": "تناسخ",
    "rebirth": "إعادة ميلاد",
    "time travel": "سفر عبر الزمن",
    "magic": "سحر",
    "urban": "حضري",
    "modern": "حديث",
    "harem": "حريم",
    "yaoi": "ياوي",
    "yuri": "يوري",
    "shounen": "شونين",
    "shoujo": "شوجو",
    "seinen": "سينين",
    "josei": "جوسي",
    "tragedy": "مأساة",
    "mature": "ناضج",
    "adult": "بالغين",
    "smut": "فاحش",
    "ecchi": "إتشي",
    "shounen ai": "شونين آي",
    "shoujo ai": "شوجو آي",
    "gender bender": "تبديل الجنس",
    "military": "عسكري",
    "political": "سياسي",
    "crime": "جريمة",
    "detective": "تحقيق",
    "steampunk": "ستيمبانك",
    "cyberpunk": "سايبربانك",
    "apocalyptic": "نهاية العالم",
    "post-apocalyptic": "ما بعد نهاية العالم",
    "survival": "نجاة",
    "revenge": "انتقام",
    "system": "نظام",
    "lgbtq+": "مثليين",
    "business": "أعمال",
    "medical": "طبي",
    "music": "موسيقى",
    "parody": "محاكاة ساخرة",
    "satire": "سخرية",
    "philosophy": "فلسفة",
    "religious": "ديني",
    "mythology": "أساطير",
    "folklore": "فلكلور",
    "fairytale": "حكاية خيالية",
    "dystopian": "بائس",
    "utopian": "مثالي",
    "space opera": "أوبرا الفضاء",
    "western": "غربي",
    "eastern": "شرقي",
    "contemporary": "معاصر",
    "parallel world": "عالم موازي",
    "transmigration": "انتقال",
    "dungeon": "زنزانة",
    "tower": "برج",
    "rpg": "آر بي جي",
    "litrpg": "ليت آر بي جي",
    "progression": "تقدم",
    "overpowered": "قوي جداً",
    "weak to strong": "من الضعف للقوة",
    "antihero": "بطل مضاد",
    "villain": "شرير",
    "hero": "بطل",
    "academy": "أكاديمية",
    "clan": "عشيرة",
    "kingdom building": "بناء مملكة",
    "empire": "إمبراطورية",
    "war": "حرب",
    "battle": "معركة",
    "tournament": "بطولة",
    "friendship": "صداقة",
    "family": "عائلة",
    "betrayal": "خيانة",
    "loyalty": "ولاء",
    "sacrifice": "تضحية",
    "redemption": "فداء"
  };
  
  // Convert to lowercase for case-insensitive matching
  const normalizedGenre = genreNameEnglish.toLowerCase().trim();
  
  // Return translation if found, otherwise return original
  return genreTranslations[normalizedGenre] || genreNameEnglish;
};
